export const HALOGRID_REGION_BASES = [
  {
    id: 'us-east-1',
    name: 'US East (N. Virginia)',
    code: 'IAD',
    lat: 38.9,
    lng: -77.0,
    carbon: 320,
    renewable: 42,
    load: 67,
    waterStress: 0.3,
    provider: 'AWS',
  },
  {
    id: 'us-west-2',
    name: 'US West (Oregon)',
    code: 'PDX',
    lat: 45.5,
    lng: -122.6,
    carbon: 85,
    renewable: 91,
    load: 44,
    waterStress: 0.2,
    provider: 'AWS',
  },
  {
    id: 'eu-west-1',
    name: 'Europe (Ireland)',
    code: 'DUB',
    lat: 53.3,
    lng: -6.3,
    carbon: 185,
    renewable: 72,
    load: 55,
    waterStress: 0.1,
    provider: 'AWS',
  },
  {
    id: 'eu-central-1',
    name: 'Europe (Frankfurt)',
    code: 'FRA',
    lat: 50.1,
    lng: 8.7,
    carbon: 290,
    renewable: 55,
    load: 71,
    waterStress: 0.4,
    provider: 'AWS',
  },
  {
    id: 'ap-southeast-1',
    name: 'Asia Pacific (Singapore)',
    code: 'SIN',
    lat: 1.35,
    lng: 103.8,
    carbon: 480,
    renewable: 12,
    load: 82,
    waterStress: 0.7,
    provider: 'AWS',
  },
  {
    id: 'ap-northeast-1',
    name: 'Asia Pacific (Tokyo)',
    code: 'NRT',
    lat: 35.7,
    lng: 139.7,
    carbon: 390,
    renewable: 28,
    load: 75,
    waterStress: 0.5,
    provider: 'AWS',
  },
  {
    id: 'ca-central-1',
    name: 'Canada (Central)',
    code: 'YUL',
    lat: 45.5,
    lng: -73.6,
    carbon: 28,
    renewable: 97,
    load: 38,
    waterStress: 0.1,
    provider: 'AWS',
  },
  {
    id: 'sa-east-1',
    name: 'South America (Sao Paulo)',
    code: 'GRU',
    lat: -23.5,
    lng: -46.6,
    carbon: 62,
    renewable: 88,
    load: 49,
    waterStress: 0.6,
    provider: 'AWS',
  },
  {
    id: 'af-south-1',
    name: 'Africa (Cape Town)',
    code: 'CPT',
    lat: -33.9,
    lng: 18.4,
    carbon: 610,
    renewable: 8,
    load: 88,
    waterStress: 0.8,
    provider: 'AWS',
  },
  {
    id: 'me-south-1',
    name: 'Middle East (Bahrain)',
    code: 'BAH',
    lat: 26.2,
    lng: 50.6,
    carbon: 520,
    renewable: 6,
    load: 79,
    waterStress: 0.9,
    provider: 'AWS',
  },
] as const
