import type {
  CiRouteResponse,
  CommandCenterSnapshot,
  ControlSurfaceOverview,
  ControlSurfaceProviderNode,
  HallOGridSnapshot,
  LandingSnapshot,
  LiveSystemSnapshot,
  WorldRegionState,
} from '@/types/control-surface'

const UNAVAILABLE_DATASETS: LiveSystemSnapshot['providers']['datasets'] = [
  { name: 'aqueduct', verificationStatus: 'unavailable', datasetVersion: null, manifestHash: null, computedHash: null },
  { name: 'aware', verificationStatus: 'unavailable', datasetVersion: null, manifestHash: null, computedHash: null },
  { name: 'wwf', verificationStatus: 'unavailable', datasetVersion: null, manifestHash: null, computedHash: null },
  { name: 'nrel', verificationStatus: 'unavailable', datasetVersion: null, manifestHash: null, computedHash: null },
]

const OFFLINE_PROVIDER_NODES: ControlSurfaceProviderNode[] = [
  'WATTTIME_MOER',
  'GRIDSTATUS',
  'EIA_930',
  'EMBER_STRUCTURAL_BASELINE',
  'ONTARIO_IESO',
  'QUEBEC_HYDRO',
  'BC_GOV',
].map((id) => ({
  id,
  label: id.replace(/_/g, ' '),
  providerType: 'carbon',
  status: 'offline',
  statusReasonCode: 'OFFLINE',
  statusLabel: 'offline',
  freshnessSec: null,
  latencyMs: null,
  confidence: null,
  mirrored: id === 'EMBER_STRUCTURAL_BASELINE',
  lineageCount: 0,
  mode: 'fallback',
  signalAuthority: 'fallback',
  degradedReason: 'Canonical engine origin is unavailable.',
  mirrorVersion: null,
  ttlSec: null,
  provenanceStatus: null,
}))

const OFFLINE_WORLD_NODES: WorldRegionState[] = [
  { region: 'us-west-2', label: 'US West 2', x: 14, y: 25 },
  { region: 'us-east-1', label: 'US East 1', x: 31, y: 26 },
  { region: 'ca-east-1', label: 'CA East 1', x: 27, y: 20 },
  { region: 'eu-west-1', label: 'EU West 1', x: 50, y: 22 },
  { region: 'eu-central-1', label: 'EU Central 1', x: 56, y: 23 },
  { region: 'eu-north-1', label: 'EU North 1', x: 57, y: 16 },
  { region: 'ap-southeast-1', label: 'AP SouthEast 1', x: 79, y: 34 },
].map((node) => ({
  ...node,
  state: 'blocked' as const,
  decisionFrameId: null,
  action: null,
  reasonCode: 'ENGINE_UNAVAILABLE',
  confidenceTier: 'low' as const,
  freshnessState: 'stale' as const,
  pressureLevel: 'high' as const,
  signalConfidence: null,
  decisionState: 'blocked' as const,
  providerHealth: { healthy: 0, degraded: 0, offline: OFFLINE_PROVIDER_NODES.length },
  selected: false,
}))

const FALLBACK_LIVE_DECISION: CiRouteResponse = {
  decision: 'deny',
  decisionMode: 'runtime_authorization',
  reasonCode: 'ENGINE_UNAVAILABLE',
  decisionFrameId: 'engine-unavailable',
  selectedRunner: 'unavailable',
  selectedRegion: 'unavailable',
  recommendation: 'Canonical engine origin is unavailable.',
  signalConfidence: 0,
  fallbackUsed: true,
  signalMode: 'fallback',
  accountingMethod: 'average',
  notBefore: null,
  proofHash: 'unavailable',
  waterAuthority: {
    authorityMode: 'fallback',
    scenario: 'current',
    confidence: 0,
    supplierSet: [],
    evidenceRefs: [],
    facilityId: null,
    telemetryRef: null,
    bundleHash: null,
    manifestHash: null,
  },
  policyTrace: {
    policyVersion: 'offline',
    profile: 'offline',
    reasonCodes: ['ENGINE_UNAVAILABLE'],
    precedenceOverrideApplied: false,
  },
  baseline: {
    region: 'unavailable',
    carbonIntensity: 0,
    waterImpactLiters: 0,
    waterScarcityImpact: 0,
  },
  selected: {
    region: 'unavailable',
    carbonIntensity: 0,
    waterImpactLiters: 0,
    waterScarcityImpact: 0,
  },
  workloadClass: 'critical',
  decisionExplanation: {
    whyAction: 'Decisioning is blocked until the canonical engine reconnects.',
    dominantConstraint: 'Engine unavailable',
    counterfactualCondition: 'Reconnect the canonical backend origin to resume live routing.',
  },
  decisionTrust: {
    signalFreshness: {
      carbonFreshnessSec: null,
      waterFreshnessSec: null,
    },
    providerTrust: {
      carbonProvider: 'offline',
      providerTrustTier: 'low',
    },
    replayability: {
      summary: 'Replay unavailable while the engine is disconnected.',
    },
    degradedState: {
      degraded: true,
      summary: 'The control plane is running in disconnected mode.',
    },
    fallbackMode: {
      engaged: true,
      summary: 'Frontend fallback snapshot is active.',
    },
  },
  workflowOutputs: {},
  candidateEvaluations: [],
  proofRecord: {
    job_id: 'engine-unavailable',
    baseline_region: 'unavailable',
    selected_region: 'unavailable',
    carbon_delta: 0,
    water_delta: 0,
    signals_used: [],
    timestamp: new Date(0).toISOString(),
    dataset_versions: {},
    confidence_score: 0,
    proof_hash: 'unavailable',
    provider_snapshot_refs: [],
    water_bundle_hash: null,
    water_manifest_hash: null,
    supplier_refs: [],
    facility_telemetry_refs: [],
    water_scenario: 'current',
    external_policy_refs: [],
    water_evidence_refs: [],
  },
  savings: {
    carbonReductionPct: 0,
    waterImpactDeltaLiters: 0,
  },
  water: {
    selectedLiters: 0,
    baselineLiters: 0,
    selectedScarcityImpact: 0,
    baselineScarcityImpact: 0,
    intensityLPerKwh: 0,
    stressIndex: 0,
    qualityIndex: null,
    droughtRiskIndex: null,
    confidence: 0,
    source: [],
    datasetVersion: {},
    guardrailTriggered: true,
    fallbackUsed: true,
  },
  enforcementBundle: {
    kubernetes: {},
    githubActions: {
      executable: false,
      decision: 'deny',
      concurrency: {
        group: 'engine-unavailable',
        cancelInProgress: false,
      },
      maxParallel: 0,
      environment: 'offline',
      notBefore: null,
      matrixAllowedRegions: [],
    },
  },
  latencyMs: {
    total: 0,
    compute: 0,
    cacheStatus: 'fallback',
    influencedDecision: true,
    providers: {
      electricityMaps: null,
      wattTime: null,
      validation: null,
    },
    budget: {
      totalP95Ms: 100,
      computeP95Ms: 50,
    },
    withinEnvelope: false,
  },
}

export const FALLBACK_LIVE_SYSTEM_SNAPSHOT: LiveSystemSnapshot = {
  generatedAt: 'Shell ready',
  recentDecisions: {
    available: false,
    error: 'Canonical engine is unavailable.',
    items: [],
  },
  traceLedger: {
    available: false,
    error: 'Trace posture is unavailable because the canonical engine is disconnected.',
    traceAvailable: false,
    traceHash: null,
    inputSignalHash: null,
    sequenceNumber: null,
    proofAvailable: false,
    replayConsistent: null,
  },
  governance: {
    available: false,
    error: 'SAIQ state is unavailable because the canonical engine is disconnected.',
    frameworkLabel: 'SAIQ',
    active: null,
    policyState: null,
    latestDecisionAction: null,
    latestReasonCode: null,
  },
  providers: {
    available: false,
    error: 'Verified provider posture is unavailable because the canonical engine is disconnected.',
    datasets: UNAVAILABLE_DATASETS,
  },
  latency: {
    available: false,
    error: 'Live latency data is unavailable because the canonical engine is disconnected.',
    samples: null,
    p95TotalMs: null,
    p95ComputeMs: null,
    budgetTotalP95Ms: null,
    budgetComputeP95Ms: null,
    withinBudget: {
      total: null,
      compute: null,
    },
  },
}

export const FALLBACK_COMMAND_CENTER_SNAPSHOT: CommandCenterSnapshot = {
  generatedAt: 'Shell ready',
  selectedDecisionFrameId: null,
  projection: {
    dataStatus: 'broken',
    projectionLagSec: null,
    latestProjectionAt: null,
    latestCanonicalAt: null,
    quality: { suspectCount: 0, invalidCount: 0 },
    outbox: null,
  },
  header: {
    systemActive: null,
    systemStatus: 'engine-unavailable',
    saiqEnforced: null,
    traceLocked: null,
    replayVerified: null,
    detail: 'Command center is live, but the canonical engine origin is unavailable.',
  },
  world: {
    nodes: OFFLINE_WORLD_NODES,
    flows: [],
  },
  decisionCore: {
    recentDecisions: [],
    selectedDecision: null,
    selectedTrace: null,
    selectedReplay: null,
  },
  governance: {
    frameworkLabel: 'SAIQ',
    source: null,
    active: null,
    strict: null,
    enforcementMode: null,
    selectedScore: null,
    thresholds: null,
    weights: null,
    impact: {
      carbonReductionPct: null,
      waterImpactDeltaLiters: null,
      signalConfidence: null,
      constraintsApplied: 0,
      cacheHit: null,
    },
  },
  traceStream: {
    items: [],
  },
  health: {
    service: {
      status: 'shell-ready',
      proofPosture: 'Canonical engine unavailable',
      detail: 'Latency, provenance, and provider state are blocked until the frontend reconnects to the engine.',
    },
    latency: FALLBACK_LIVE_SYSTEM_SNAPSHOT.latency,
    provenance: FALLBACK_LIVE_SYSTEM_SNAPSHOT.providers,
    providers: OFFLINE_PROVIDER_NODES,
  },
}

export const FALLBACK_HALLOGRID_SNAPSHOT: HallOGridSnapshot = {
  generatedAt: 'Shell ready',
  selectedFrameId: null,
  title: 'CO2 Grid Freeview',
  subtitle: 'Public proof surface powered by CO2 Router',
  access: {
    tenantId: 'public-preview',
    entitlements: ['public_preview'],
    role: 'viewer',
    mode: 'public_preview',
    label: 'CO2 Grid Freeview',
    isReadOnlyPreview: true,
    canViewOperatorConsole: false,
    canAccessControls: false,
    canManageDoctrine: false,
    canViewCompliance: false,
    redactionDelayMinutes: 15,
    upgradePrompts: ['Request Pilot Access', 'View CO2 Grid pricing'],
    proHighlights: ['trace replay', 'counterfactual analysis', 'doctrine controls'],
    upgradeUrl: '/access',
  },
  mirror: {
    tenantId: 'public-preview',
    generatedAt: 'Shell ready',
    sourceFreshnessSec: null,
    freshnessBudgetSec: 120,
    safeDelayWindowSec: 5400,
    mirrorMode: 'hot',
    degraded: true,
    degradedReason: 'HallOGrid is in degraded mode because the canonical engine origin is unavailable.',
    laneBudgets: {
      hotP95Ms: 100,
      warmP95Ms: 250,
      coldQueued: true,
    },
    metrics: {
      decisionP50Ms: null,
      decisionP95Ms: null,
      decisionP99Ms: null,
      consoleSnapshotP50Ms: null,
      consoleSnapshotP95Ms: null,
      providerRefreshAgeSec: null,
      mirrorGenerationMs: null,
      replayGenerationMs: null,
      exportQueueDepth: 0,
    },
  },
  projection: FALLBACK_COMMAND_CENTER_SNAPSHOT.projection,
  selectedFrame: null,
  frames: [],
  world: FALLBACK_COMMAND_CENTER_SNAPSHOT.world,
  governance: FALLBACK_COMMAND_CENTER_SNAPSHOT.governance,
  traceStream: FALLBACK_COMMAND_CENTER_SNAPSHOT.traceStream,
  health: FALLBACK_COMMAND_CENTER_SNAPSHOT.health,
  transport: {
    mode: 'snapshot+stream',
    streamHealthy: false,
    snapshotUrl: '/api/control-surface/hallogrid',
    streamUrl: '/api/control-surface/hallogrid/stream',
    adapters: [
      {
        id: 'canonical-rest',
        label: 'Canonical CO2 Router mirror',
        kind: 'canonical',
        enabled: true,
        notes: 'Fallback shell is active while CO2 Grid Freeview reconnects.',
      },
      {
        id: 'polling-fallback',
        label: 'Polling fallback adapter',
        kind: 'polling',
        enabled: true,
        notes: 'Snapshot polling resumes when the live stream recovers.',
      },
    ],
  },
}

export const FALLBACK_OVERVIEW: Pick<
  ControlSurfaceOverview,
  'actionDistribution' | 'providers' | 'replay'
> = {
  actionDistribution: [],
  providers: OFFLINE_PROVIDER_NODES,
  replay: null,
}

export const FALLBACK_OVERVIEW_SNAPSHOT: ControlSurfaceOverview = {
  generatedAt: 'Shell ready',
  service: {
    status: 'degraded',
    proofPosture: 'Canonical engine unavailable',
    detail: 'The website shell is up, but the canonical engine origin is unavailable.',
  },
  impact: {
    totalDecisions: 0,
    carbonAvoidedKg: 0,
    carbonReductionMultiplier: null,
    waterShiftedLiters: 0,
    costOptimizedUsd: 0,
    delayedDecisions: 0,
  },
  liveDecision: FALLBACK_LIVE_DECISION,
  featuredDecision: FALLBACK_LIVE_DECISION,
  replay: null,
  decisions: [],
  actionDistribution: [],
  providers: OFFLINE_PROVIDER_NODES,
  scenarioPreviews: [],
  timeline: [
    {
      id: 'engine-unavailable',
      type: 'ProviderDegraded',
      label: 'Canonical engine unavailable',
      timestamp: 'Shell ready',
      severity: 'critical',
      detail: 'Reconnect the frontend to the live engine origin to restore decisioning.',
    },
  ],
  metrics: {
    fallbackRate: 100,
    highConfidenceDecisionPct: 0,
    providerDisagreementRatePct: 0,
    p50TotalMs: 0,
    p50ComputeMs: 0,
    p95TotalMs: 0,
    p95ComputeMs: 0,
    p99TotalMs: 0,
    p99ComputeMs: 0,
    currentTotalMs: 0,
    currentComputeMs: 0,
  },
  health: {
    status: 'degraded',
    timestamp: 'Shell ready',
    checks: {
      database: false,
      waterArtifacts: {
        bundlePresent: false,
        manifestPresent: false,
        schemaCompatible: false,
        regionCount: 0,
        sourceCount: 0,
        datasetHashesPresent: false,
      },
    },
    errors: ['Canonical engine origin is unavailable.'],
    sloBudgetMs: {
      totalP95Ms: 100,
      computeP95Ms: 50,
    },
  },
  slo: {
    samples: 0,
    p50: { totalMs: 0, computeMs: 0 },
    p95: { totalMs: 0, computeMs: 0 },
    p99: { totalMs: 0, computeMs: 0 },
    current: { totalMs: 0, computeMs: 0 },
    budget: { totalP95Ms: 100, computeP95Ms: 50 },
    withinBudget: { total: false, compute: false },
  },
  outbox: null,
  simulationDefaults: {
    preferredRegions: ['us-east-1', 'eu-west-1', 'us-west-2'],
    waterPolicyProfile: 'default',
    jobType: 'standard',
    criticality: 'standard',
    carbonWeight: 0.55,
    waterWeight: 0.35,
    latencyWeight: 0.05,
    costWeight: 0.05,
    allowDelay: true,
    estimatedEnergyKwh: 2.5,
  },
}

export const FALLBACK_LANDING_SNAPSHOT: LandingSnapshot = {
  generatedAt: 'Shell ready',
  liveStatus: {
    visible: true,
    generatedAt: 'Shell ready',
    lastUpdatedLabel: 'reconnecting',
    detail: 'Landing snapshot is reconnecting. The public shell stays stable while fresh live excerpts attach.',
  },
  overview: {
    actionDistribution: [],
    providers: [],
    featuredDecision: null,
    liveStrip: [],
    proofContext: {
      proofRef: null,
      governance: 'Policy-first control posture',
      traceRef: null,
    replay: 'CO2 Grid Freeview',
      provenance: 'Verified provider posture reattaches when the landing snapshot refreshes.',
    },
  },
  liveSystem: FALLBACK_LIVE_SYSTEM_SNAPSHOT,
}
